### PR TITLE
[WIP] Initial update to egui 0.19 based on glium, glow and miniquad implementations

### PR DESCRIPTION
**Pull request by EriKWDev**
This is an initial update of egui to latest.
Quite a bit has changed but thanks to https://github.com/not-fl3/egui-miniquad/blob/master/src/painter.rs, https://github.com/emilk/egui/blob/master/crates/egui_glow/src/painter.rs, and https://github.com/emilk/egui/blob/master/crates/egui_glium/src/painter.rs I was able to come quite a bit.

Sadly, the egui texture seems to be black. Input seems to be working and the shadow behind the window display correctly.

Could you perhaps have a look at what could be wrong?

image

### CODE REVIEW

**Comment by cohaereo** [comment]
Quickly looking at the issue on my way home, it seems that the font texture _does_ get uploaded, but is deleted right after the first drawn frame, though DeleteTextures is never called... I'll be taking a more extensive look when I get home

**Comment by EriKWDev** [comment]
Some things to note that might be wrong:
- I only used gl::RGBA for textures, but there is a lot of code relating to sRGBA so maybe other texture formats should be used
- The egui::TextureId::User(id) assigned to a UserTexture should probably be the same as it's OpenGL textureid, currently just setting it to self.textures.len() which is most likely wrong. This could be fixed if we stop lazily creating the textures and instead do it immediately like glow-implementation does it: https://github.com/emilk/egui/blob/d5933daee5328d3ca37741c0642d09a1e71232fb/crates/egui_glow/src/painter.rs#L523  
- I used the vertex and fragment shaders from miniquad since they supported the oldest version of glsl (100)

**Comment by EriKWDev** [comment]
Did you you find anything? :)

**Comment by cohaereo** [comment]
Sorry for the delay, I've been a bit busy.
I managed to find the issue. 

At [this line](https://github.com/EriKWDev/egui_glfw_gl/blob/master/src/painter.rs#L327), you're binding egui textures as opengl textures, which use their own internal ID (starting at zero, so binding the first egui texture as opengl texture effectively unbinds the texture)
```rs
match mesh.texture_id {
    egui::TextureId::Managed(id) | egui::TextureId::User(id) => unsafe {
        gl::BindTexture(gl::TEXTURE_2D, id as _)
    },
}
```
Mapping the IDs through a hashmap should be enough to resolve the issue.
(i just quickly binded the egui texture here, that's why it looks weird)
image

**Comment by EriKWDev** [comment]
That was it! I had already created a hashmap with the correct ids.. Just didn't use it there correctly.

Changed that line to:
```rust
let it = self
    .textures
    .get(&mesh.texture_id)
    .expect("Textures should have been added to hash map by now");

unsafe {
    gl::BindTexture(
        gl::TEXTURE_2D,
        it.texture
            .expect("Texture should have a valid OpenGL id now"),
    );
}
```

The assumptions in the `.expect()` might be incorrect though.

image

The colors look off though

**Comment by EriKWDev** [comment]
There we go

image

**Comment by EriKWDev** [comment]
Getting segfaults in some of my more complex UI apps.. Will try to isolate

**Comment by cohaereo** [comment]
Is this ready now?

**Comment by EriKWDev** [comment]
I haven't tested very extensibly, but with the new safety checks I haven't gotten a segfault yet in my applications.

I feel like the API from the User's point of view could probably be made simpler to use, but that should probably be a separate PR

**Comment by rdeepak2002** [comment]
Thanks for making this! It seems to work well on my end.

**Pull request merged**
